donation/urls.py
from django.urls import path
from . import views

app_name = 'donation'

urlpatterns = [
    path('', views.home, name='home'),
    path('post', views.post_donation, name= 'post'),
]

main/urls.py
from django.urls import path, include

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('confirm', views.confirm, name='confirm'),
    path('cases', views.cases, name='cases'),
    path('about-us', views.aboutus, name='about-us'),
    path('donations', views.donate_list, name='donasi'),
    path('contact-us', views.contactus, name='contact-us'),
]

tkppw/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('report/', include('report.urls')),
    path('services/', include('services.urls')),
    path('donation/', include('donation.urls')),
    path('feedback/', include('feedback.urls')),
    path('about-us/', views.aboutus),
    path('cases/', views.cases),
    path('donations/', views.donate_list),
    
]

donation/models.py
from django.db import models

# Create your models here.
class Donate(models.Model):
    name = models.CharField(max_length=50)
    email =  models.CharField(max_length=30)
    nominal = models.IntegerField(max_length=30)

donation/forms.py
from django import forms

class donateform(forms.Form):
    error_messages = {
        'required': 'This field is required.'
    }
    attrs = {
        'class' : 'form-control'
    }
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Nama ', max_length=50, required=True)
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label = 'Email ', max_length=30, required=True)
    nominal = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label = 'Nominal ',max_length=30, required=True)

donation/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from donation.models import Donate
from donation.forms import donateform 

# Create your views here.
def home(request):
    form_tambah = donateform()
    data = Donate.objects.all()
    response = {'form_tambah' : form_tambah, 'data' : data}
    return render(request, 'donation.html', response)



def post_donation(request):
    if request.method == 'POST':
        form = donateform(request.POST or None)
        response_data = {}
        if form.is_valid():
            response_data['name'] = request.POST['name']
            response_data['email'] = request.POST['email']
            response_data['nominal'] = request.POST['nominal']

            data_donation = Donate(name=response_data['name'],
                                   email=response_data['email'],
                                   nominal=response_data['nominal'],
                                   )
            data_donation.save()
            return redirect('main:confirm')

donation/templates/donation.html
{% extends 'base.html' %}   
{% load static %}

{% block meta %}

{% endblock meta %}

{% block content %} 

<div style="text-align: center;
padding: 1%;padding-bottom: 3%;"><h1>Donate</h1><br>
<h5>Tolong tuliskan pada halaman ini nama, email serta nominal yang ingin disumbangkan.<br><br>
    Informasi lebih lanjut akan diberikan kepada email yang diberikan.
</h5></div>
    
   </div>
<div style="margin: auto;
            border: 2px solid black;
            border-radius: 10px;
            width: 75%;
            padding: 20px">
    <form method= "POST" action="{% url 'donation:post' %}">
        {% csrf_token %}
        {{ form_tambah.as_p }}
        <div>
            <a href="{% url 'main:home' %}" style="text-decoration: none; color: #000000;"><button class="button cancel-button">Cancel</a>
            <button class="button submit-button">Submit</a>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock content %}